[package]
name = "blox"
version = "0.1.0"
authors = ["acuaro-codes <67112172+acuaro-codes@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "2"